export const situations = [
  ["introductions", "Apresentações"],
  ["conversation", "Conversas básicas"],
  ["questions", "Perguntas"],
  ["restaurant", "Restaurante"],
  ["cafe", "Cafeteria"],
  ["supermarket", "Supermercado"],
  ["shopping", "Compras"],
  ["directions", "Direções"],
  ["transport", "Transporte público"],
  ["taxi", "Táxi"],
  ["airport", "Aeroporto"],
  ["immigration", "Imigração"],
  ["hotel", "Hotel"],
  ["health", "Saúde"],
  ["emergency", "Emergências"],
  ["technology", "Tecnologia"],
  ["work", "Trabalho"],
  ["housing", "Moradia"],
  ["social", "Vida social"],
  ["travel-problems", "Problemas em viagens"],
];
export const categories = [
  ["noun", "Substantivos"],
  ["verb", "Verbos"],
  ["adjective", "Adjetivos"],
  ["adverb", "Advérbios"],
  ["other", "Palavras de apoio"],
  ["phrase", "Frases / expressões"],
  ["paragraph", "Parágrafos"],
];
