/* Lote inicial de 30 itens para testar. IDs estáveis; formas verbais não duplicam o vocabulário. */
window.STUDY_DATA = [
  {
    id: "en-n001",
    category: "noun",
    english: "ticket",
    portuguese: "bilhete / passagem",
    situations: ["transport", "airport"],
    missions: ["transport-ticket"],
    level: 1,
    example: {
      english: "Where can I buy a ticket?",
      portuguese: "Onde posso comprar um bilhete?",
    },
  },
  {
    id: "en-n002",
    category: "noun",
    english: "bill",
    portuguese: "conta (do restaurante)",
    situations: ["restaurant", "cafe"],
    missions: ["restaurant-order"],
    level: 1,
    example: {
      english: "Could I have the bill, please?",
      portuguese: "Você poderia trazer a conta, por favor?",
    },
    note: "Em um restaurante na Irlanda, bill é a palavra habitual para a conta.",
  },
  {
    id: "en-n003",
    category: "noun",
    english: "platform",
    portuguese: "plataforma (de estação)",
    situations: ["transport"],
    missions: ["transport-ticket"],
    level: 1,
    example: {
      english: "Which platform does the train leave from?",
      portuguese: "De qual plataforma o trem sai?",
    },
  },
  {
    id: "en-n004",
    category: "noun",
    english: "room",
    portuguese: "quarto",
    situations: ["hotel", "housing"],
    missions: ["hotel-check-in"],
    level: 1,
    example: {
      english: "Is the room ready?",
      portuguese: "O quarto está pronto?",
    },
  },
  {
    id: "en-n005",
    category: "noun",
    english: "shift",
    portuguese: "turno de trabalho",
    situations: ["work"],
    missions: ["work-instructions"],
    level: 1,
    example: {
      english: "My shift starts at two.",
      portuguese: "Meu turno começa às duas.",
    },
  },
  {
    id: "en-v001",
    category: "verb",
    english: "go",
    portuguese: "ir",
    situations: ["transport", "work"],
    missions: ["transport-ticket", "work-instructions"],
    level: 1,
    example: {
      english: "I go to work by bus.",
      portuguese: "Eu vou para o trabalho de ônibus.",
    },
    forms: {
      present: {
        english: "I go to work by bus.",
        portuguese: "Eu vou para o trabalho de ônibus.",
      },
      past: {
        english: "I went to work by bus yesterday.",
        portuguese: "Eu fui para o trabalho de ônibus ontem.",
      },
      participle: {
        english: "She has gone home.",
        portuguese: "Ela foi para casa (e está fora daqui).",
      },
      thirdPerson: {
        english: "She goes to work by bus.",
        portuguese: "Ela vai para o trabalho de ônibus.",
      },
      ing: {
        english: "I am going to work now.",
        portuguese: "Eu estou indo para o trabalho agora.",
      },
    },
  },
  {
    id: "en-v002",
    category: "verb",
    english: "buy",
    portuguese: "comprar",
    situations: ["shopping", "supermarket", "transport"],
    missions: ["transport-ticket"],
    level: 1,
    example: {
      english: "I buy my tickets online.",
      portuguese: "Eu compro meus bilhetes pela internet.",
    },
    forms: {
      present: {
        english: "I buy my tickets online.",
        portuguese: "Eu compro meus bilhetes pela internet.",
      },
      past: {
        english: "I bought a ticket yesterday.",
        portuguese: "Eu comprei um bilhete ontem.",
      },
      participle: {
        english: "I have already bought a ticket.",
        portuguese: "Eu já comprei um bilhete.",
      },
      thirdPerson: {
        english: "She buys her tickets online.",
        portuguese: "Ela compra os bilhetes dela pela internet.",
      },
      ing: {
        english: "I am buying a ticket.",
        portuguese: "Eu estou comprando um bilhete.",
      },
    },
  },
  {
    id: "en-v003",
    category: "verb",
    english: "need",
    portuguese: "precisar de",
    situations: ["work", "hotel", "emergency"],
    missions: ["work-instructions", "hotel-check-in"],
    level: 1,
    example: {
      english: "I need some help.",
      portuguese: "Eu preciso de ajuda.",
    },
    forms: {
      present: {
        english: "I need a clean towel.",
        portuguese: "Eu preciso de uma toalha limpa.",
      },
      past: {
        english: "I needed some help yesterday.",
        portuguese: "Eu precisei de ajuda ontem.",
      },
      participle: {
        english: "I have needed help a few times this week.",
        portuguese: "Eu precisei de ajuda algumas vezes nesta semana.",
      },
      thirdPerson: {
        english: "She needs a clean towel.",
        portuguese: "Ela precisa de uma toalha limpa.",
      },
    },
  },
  {
    id: "en-v004",
    category: "verb",
    english: "ask",
    portuguese: "perguntar / pedir",
    situations: ["questions", "work", "conversation"],
    missions: ["work-instructions", "conversation-clarify"],
    level: 1,
    example: {
      english: "Can I ask a question?",
      portuguese: "Posso fazer uma pergunta?",
    },
    note: "Ask a question = fazer uma pergunta; ask for help = pedir ajuda.",
    forms: {
      present: {
        english: "I ask for help when I need it.",
        portuguese: "Eu peço ajuda quando preciso.",
      },
      past: {
        english: "I asked for help yesterday.",
        portuguese: "Eu pedi ajuda ontem.",
      },
      participle: {
        english: "I have already asked for help.",
        portuguese: "Eu já pedi ajuda.",
      },
      thirdPerson: {
        english: "She asks for help when she needs it.",
        portuguese: "Ela pede ajuda quando precisa.",
      },
      ing: {
        english: "I am asking for help.",
        portuguese: "Eu estou pedindo ajuda.",
      },
    },
  },
  {
    id: "en-v005",
    category: "verb",
    english: "work",
    portuguese: "trabalhar",
    situations: ["work", "introductions"],
    missions: ["work-instructions"],
    level: 1,
    example: {
      english: "I work in Leixlip.",
      portuguese: "Eu trabalho em Leixlip.",
    },
    forms: {
      present: {
        english: "I work in Leixlip.",
        portuguese: "Eu trabalho em Leixlip.",
      },
      past: {
        english: "I worked yesterday.",
        portuguese: "Eu trabalhei ontem.",
      },
      participle: {
        english: "I have worked here for a year.",
        portuguese: "Eu trabalho aqui há um ano.",
      },
      thirdPerson: {
        english: "She works in Leixlip.",
        portuguese: "Ela trabalha em Leixlip.",
      },
      ing: {
        english: "I am working today.",
        portuguese: "Eu estou trabalhando hoje.",
      },
    },
  },
  {
    id: "en-a001",
    category: "adjective",
    english: "available",
    portuguese: "disponível",
    situations: ["hotel", "restaurant"],
    missions: ["hotel-check-in", "restaurant-order"],
    level: 1,
    example: {
      english: "Is a table available?",
      portuguese: "Há uma mesa disponível?",
    },
  },
  {
    id: "en-a002",
    category: "adjective",
    english: "late",
    portuguese: "atrasado",
    situations: ["transport", "work"],
    missions: ["transport-ticket", "work-instructions"],
    level: 1,
    example: {
      english: "The bus is late.",
      portuguese: "O ônibus está atrasado.",
    },
  },
  {
    id: "en-a003",
    category: "adjective",
    english: "clean",
    portuguese: "limpo",
    situations: ["hotel", "work"],
    missions: ["hotel-check-in", "work-instructions"],
    level: 1,
    example: {
      english: "The room is clean.",
      portuguese: "O quarto está limpo.",
    },
  },
  {
    id: "en-d001",
    category: "adverb",
    english: "slowly",
    portuguese: "devagar",
    situations: ["conversation", "work"],
    missions: ["conversation-clarify", "work-instructions"],
    level: 1,
    example: {
      english: "Please speak slowly.",
      portuguese: "Por favor, fale devagar.",
    },
  },
  {
    id: "en-d002",
    category: "adverb",
    english: "nearby",
    portuguese: "por perto",
    situations: ["directions", "hotel"],
    missions: ["hotel-check-in"],
    level: 1,
    example: {
      english: "Is there a shop nearby?",
      portuguese: "Há uma loja por perto?",
    },
  },
  {
    id: "en-o001",
    category: "other",
    english: "where",
    portuguese: "onde",
    situations: ["questions", "directions", "transport"],
    missions: ["transport-ticket"],
    level: 1,
    example: {
      english: "Where is the bus stop?",
      portuguese: "Onde fica o ponto de ônibus?",
    },
  },
  {
    id: "en-o002",
    category: "other",
    english: "how much",
    portuguese: "quanto (para perguntar preço ou quantidade)",
    situations: ["questions", "shopping", "restaurant"],
    missions: ["restaurant-order"],
    level: 1,
    example: {
      english: "How much is it?",
      portuguese: "Quanto custa?",
    },
  },
  {
    id: "en-o003",
    category: "other",
    english: "before",
    portuguese: "antes de",
    situations: ["work", "transport"],
    missions: ["work-instructions"],
    level: 1,
    example: {
      english: "Please finish this before lunch.",
      portuguese: "Por favor, termine isto antes do almoço.",
    },
  },
  {
    id: "en-p001",
    category: "phrase",
    english: "Could you say that again, please?",
    portuguese: "Você poderia repetir isso, por favor?",
    situations: ["conversation", "work"],
    missions: ["conversation-clarify"],
    level: 1,
  },
  {
    id: "en-p002",
    category: "phrase",
    english: "Could you speak a bit more slowly, please?",
    portuguese: "Você poderia falar um pouco mais devagar, por favor?",
    situations: ["conversation", "work"],
    missions: ["conversation-clarify"],
    level: 1,
  },
  {
    id: "en-p003",
    category: "phrase",
    english: "Sorry, I didn't understand.",
    portuguese: "Desculpe, eu não entendi.",
    situations: ["conversation", "work"],
    missions: ["conversation-clarify"],
    level: 1,
  },
  {
    id: "en-p004",
    category: "phrase",
    english: "Does this bus go to Dublin?",
    portuguese: "Este ônibus vai para Dublin?",
    situations: ["transport"],
    missions: ["transport-ticket"],
    level: 1,
  },
  {
    id: "en-p005",
    category: "phrase",
    english: "Where can I buy a ticket?",
    portuguese: "Onde posso comprar um bilhete?",
    situations: ["transport", "airport"],
    missions: ["transport-ticket"],
    level: 1,
  },
  {
    id: "en-p006",
    category: "phrase",
    english: "A table for two, please.",
    portuguese: "Uma mesa para duas pessoas, por favor.",
    situations: ["restaurant"],
    missions: ["restaurant-order"],
    level: 1,
  },
  {
    id: "en-p007",
    category: "phrase",
    english: "Could I have the bill, please?",
    portuguese: "Você poderia trazer a conta, por favor?",
    situations: ["restaurant", "cafe"],
    missions: ["restaurant-order"],
    level: 1,
  },
  {
    id: "en-p008",
    category: "phrase",
    english: "I have a reservation under the name Cardona.",
    portuguese: "Eu tenho uma reserva em nome de Cardona.",
    situations: ["hotel", "restaurant"],
    missions: ["hotel-check-in"],
    level: 1,
  },
  {
    id: "en-p009",
    category: "phrase",
    english: "What should I do next?",
    portuguese: "O que eu devo fazer agora (como próxima tarefa)?",
    situations: ["work"],
    missions: ["work-instructions"],
    level: 1,
  },
  {
    id: "en-p010",
    category: "phrase",
    english: "Do I need to finish this today?",
    portuguese: "Eu preciso terminar isto hoje?",
    situations: ["work"],
    missions: ["work-instructions"],
    level: 1,
  },
  {
    id: "en-r001",
    category: "paragraph",
    english:
      "I have a reservation for two nights. My name is Ricardo Cardona. Is breakfast included?",
    portuguese:
      "Eu tenho uma reserva para duas noites. Meu nome é Ricardo Cardona. O café da manhã está incluído?",
    situations: ["hotel"],
    missions: ["hotel-check-in"],
    level: 1,
  },
  {
    id: "en-r002",
    category: "paragraph",
    english:
      "My shift starts at two. I need to clean this room first. If I have a question, I ask my supervisor.",
    portuguese:
      "Meu turno começa às duas. Eu preciso limpar este quarto primeiro. Se eu tiver uma dúvida, eu pergunto ao meu supervisor.",
    situations: ["work"],
    missions: ["work-instructions"],
    level: 1,
  },
];
